### ISSUE TITLE
Very Slow

### ISSUE THREAD

**Issue by SamuelGabriel** [deepmind/neural_testbed#4]
Hi There,

For me running evaluations is very slow. I use a GPU, but still evaluating the `baseline:uniform_class_probs` on `leaderboard.CLASSIFICATION_2D_TEST` takes very long. At least 20 minutes. I never finished the run, not even the first test.

Any idea?

**Comment by iosband** [comment]
Hi there - can you provide a reproducing script, or maybe even a colab notebook?
How long does *each* problem_id take?

You can see on the https://bit.ly/neural_testbed_tutorial that even with an underpowered colab CPU each problem_id only takes a few seconds...

**Comment by SamuelGabriel** [comment]
Good point! I will try to figure out the diff to the Colab. :)

**Comment by SamuelGabriel** [comment]
I still don't know what was the course of the slowness, but I will stop investigating, as it works fine now when I create an environment from scratch with the PR + Python 3.9.6.

Best,

Sam
